env:
  browser: true
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  react/jsx-uses-react: 'error'
  react/jsx-uses-vars: 'error'
  unicorn/filename-case:
    - error
    - case: kebabCase
